### ISSUE TITLE
File not visible in some folder

### ISSUE THREAD

**Issue by psc2350** [balloy/aria2-ftp#1] opened 2018-09-30 06:43 UTC
Greetings,
I recently did a reinstall of my Windows 7. Since then, some of the file in my server may not be visible in the client while the file is actually there. I am running a Windows 7 64 bit. Is there any requirement needed to install in order for it to run properly?

**Comment by balloy** [comment] 2018-10-02 20:52
I'm not sure what's the question. Do you mean you can't run aria2-ftp any more after the OS reinstallation? Have you tried to reinstall aria2-ftp and is there any error while launching it?
As for the requirement, it should be same as Electron and Windows 7 is supported.
https://electronjs.org/docs/tutorial/support

**Comment by psc2350** [comment] 2018-10-03 02:37
Sorry for not being specific. What I meant was that some folder appears to be empty when it actually contains files that are not hidden.

**Comment by balloy** [comment] 2018-10-03 03:19
Do you mean some local folder can't be properly listed in aria2-ftp? 
In that case I'll suggest you check the folder permission first. Another thing worth trying is going to menu > View > Toggle Developer Tools, then refresh the local folder and check if there's any warning/error messages.

**Comment by psc2350** [comment] 2018-10-03 04:45
I meant the server folder that I am connecting to.
I believe is because the folder name path is too long. (Not so sure)
I have this big folder (A) containing many sub-folder with different names. Seems like the one with the shortest name display properly, and the one with longer name does not. There is also a sub-folder (B) with relative short name under the big folder (A). Opening this folder will display its sub-folder (C), which is the only thing in that directory. However, after expanding this sub-folder (C), the files that are supposed to be there is not displayed. This is why I suspect the issue to be because of the length of folder name.

**Comment by balloy** [comment] 2018-10-04 15:03
Thanks for the clarification. To help troubleshoot the issue, please provide more details:
1. Is the FTP server public? If yes please provide a test account, and you can skip the rest questions:)
2. Is there same issue with other FTP clients (e.g. FileZilla client)?
3. When you said Windows 7 64 bit, is the OS for the FTP client or the FTP server?
And below questions are to help me setup a local FTP server to replicate the issue.
4. What's the FTP server software and its version?
5. Please provide the full path of the "big folder (A)", or even better, the "sub-folder (C)".

**Comment by psc2350** [comment] 2018-10-04 15:29
I sent you a test account information via email with the same email subject as this issue's title. (balloy@gmail.com)

**Comment by balloy** [comment] 2018-10-04 17:05
Thanks. I've got the test account and be able to replicate the issue. Will update later once there's a solution.

**Comment by balloy** [comment] 2018-10-06 19:38
The issue is caused by limitation of jsftp.ls, I've used CMD+MLSD instead to fix the issue. Please help verify it with latest version v0.1.6, thanks.

**Comment by psc2350** [comment] 2018-10-07 01:15
Thanks for the update. The latest version seems to work really good. Just wanna suggest one more feature. It will be nice to implement savings of username and password.

**Comment by balloy** [comment] 2018-10-07 22:05
Thanks for the confirmation, I'm closing the issue now.

As for saving user/password, I did consider adding a site manager feature but it seemed too much effort. So there's no plan to implement it in any near future. Sorry about that.
Anyway there're 2 tips might help a little bit:
1. Like Filezilla, you can input the whole FTP URL (e.g. ftp://user:password@host:port) into the Host input box then click the button Connect.
2. Or, you can use the command line parameter --ftp.

**Closed as completed by balloy** 2018-10-07 22:05 UTC
